version: '3'

includes:
  common: ./build/Taskfile.yaml
  windows: ./build/windows/Taskfile.yaml
  darwin: ./build/darwin/Taskfile.yaml
  linux: ./build/linux/Taskfile.yaml

vars:
  APP_NAME: "Kanmail"
  BIN_DIR: "bin"
  VITE_PORT: '{{.WAILS_VITE_PORT | default 9245}}'

tasks:
  build:
    summary: Builds the application
    cmds:
      - task: "{{OS}}:build"

  package:
    summary: Packages a production build of the application
    cmds:
      - task: "{{OS}}:package"

  run:
    summary: Runs the application
    cmds:
      - task: "{{OS}}:run"

  dev:
    summary: Runs the application in development mode
    cmds:
      - wails3 dev -config ./build/config.yaml -port {{.VITE_PORT}}
