#!/bin/sh

set -euxo pipefail

export KANMAIL_PROFILE=dev-fake
export KANMAIL_DEBUG_LICENSED=1
export KANMAIL_DEBUG_CACHES_DISABLE=1
export KANMAIL_DEBUG_FAKE_IMAP=${1:-on}
export KANMAIL_DEBUG_WINDOW_WIDTH=1680
export KANMAIL_DEBUG_WINDOW_HEIGHT=1080
wails3 task dev
