package constants

import "os"

var (
	ENV_DEBUG_PRETTY_LOGS    = os.Getenv("KANMAIL_DEBUG_PRETTY_LOGS")
	ENV_DEBUG_NO_AUTOCLOSE   = os.Getenv("KANMAIL_DEBUG_NO_AUTOCLOSE")
	ENV_DEBUG_CACHES_DISABLE = os.Getenv("KANMAIL_DEBUG_CACHES_DISABLE")
	ENV_DEBUG_OFFLINE        = os.Getenv("KANMAIL_DEBUG_OFFLINE")
	ENV_DEBUG_FAKE_IMAP      = os.Getenv("KANMAIL_DEBUG_FAKE_IMAP")
	ENV_DEBUG_START_APP      = os.Getenv("KANMAIL_DEBUG_START_APP")
)
