package constants

const (
	ENV_DEBUG_PRETTY_LOGS    = "KANMAIL_DEBUG_PRETTY_LOGS"
	ENV_DEBUG_NO_AUTOCLOSE   = "KANMAIL_DEBUG_NO_AUTOCLOSE"
	ENV_DEBUG_CACHES_DISABLE = "KANMAIL_DEBUG_CACHES_DISABLE"
	ENV_DEBUG_OFFLINE        = "KANMAIL_DEBUG_OFFLINE"
	ENV_DEBUG_FAKE_IMAP      = "KANMAIL_DEBUG_FAKE_IMAP"
)
