//go:build !production

package constants

import (
	"os"
)

var (
	BACKEND_API_KEY             = os.Getenv("KANMAIL_BACKEND_API_KEY")
	OAUTH_GMAIL_CLIENT_ID       = os.Getenv("KANMAIL_GMAIL_OAUTH_CLIENT_ID")
	OAUTH_GMAIL_CLIENT_SECRET   = os.Getenv("KANMAIL_OAUTH_GMAIL_CLIENT_SECRET")
	OAUTH_OUTLOOK_CLIENT_ID     = os.Getenv("KANMAIL_OAUTH_OUTLOOK_CLIENT_ID")
	OAUTH_OUTLOOK_CLIENT_SECRET = os.Getenv("KANMAIL_OAUTH_OUTLOOK_CLIENT_SECRET")
)
