name: Kanmail v2 CI

on:
  push:

jobs:
  test:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - run: sudo apt-get update && sudo apt-get install -y libwebkit2gtk-4.1-dev
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - run: go mod tidy
      - run: go test -v ./internal/...
      - run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go install honnef.co/go/tools/cmd/staticcheck@latest
          export PATH="$HOME/go/bin:$PATH"
          mkdir frontend/dist
          touch frontend/dist/index.js
      - uses: pre-commit/action@v3.0.1
